[package]
name = "test-kernel"
version = "0.2.0"
authors = ["Luo Jia <me@luojia.cc>", "YdrMaster <ydrml@hotmail.com>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sbi-rt = "0.0.1"
riscv = "0.9.0"
spin = "0.9"
r0 = "1"
uart_16550 = "0.2"
dtb-walker = "=0.2.0-alpha.3"
